name: "TechTrends - Package with Docker"

on:
  push:
    branches:
      - main

      # Specifiing the files that will trigger this workflow is not a project
    # requirement, but it can help reduce unnecessary workflow runs.
    paths:
      - .github/workflows/techtrends-dockerhub.yml
      - Dockerfile
      - requirements.txt
      - app.py
      - __init__.py
      - init_db.py
      - schema.sql
      - static/**
      - templates/**

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Enable the execution of different multi-architecture containers
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Use extended Docker CLI build capabilities
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub registry
      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image to DockerHub registry
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}/techtrends:latest